def show_screen() -> None: ...
def clear_screen() -> None: ...
def set_pixel(x: int, y: int, color: tuple[int, int, int] = None) -> None: ...
def get_pixel(x: int, y: int) -> tuple[int, int, int]: ...
def draw_string(x: int, y: int, text: str, color: tuple[int, int, int] = None, size: str = None) -> None: ...
