DTEXT_LEFT          : int = ...
DTEXT_CENTER        : int = ...
DTEXT_RIGHT         : int = ...
DTEXT_TOP           : int = ...
DTEXT_MIDDLE        : int = ...
DTEXT_BOTTOM        : int = ...
C_WHITE             : int = ...
C_LIGHT             : int = ...
C_DARK              : int = ...
C_BLACK             : int = ...
C_NONE              : int = ...
C_INVERT            : int = ...
C_LIGHTEN           : int = ...
C_DARKEN            : int = ...
IMAGE_MONO          : int = ...
IMAGE_MONO_ALPHA    : int = ...
IMAGE_GRAY          : int = ...
IMAGE_GRAY_ALPHA    : int = ...
IMAGE_RGB565        : int = ...
IMAGE_RGB565A       : int = ...
IMAGE_P8_RGB565     : int = ...
IMAGE_P8_RGB565A    : int = ...
IMAGE_P4_RGB565     : int = ...
IMAGE_P4_RGB565A    : int = ...
GETKEY_MOD_SHIFT    : int = ...
GETKEY_MOD_ALPHA    : int = ...
GETKEY_BACKLIGHT    : int = ...
GETKEY_MENU         : int = ...
GETKEY_REP_ARROWS   : int = ...
GETKEY_REP_ALL      : int = ...
GETKEY_REP_PROFILE  : int = ...
GETKEY_FEATURES     : int = ...
GETKEY_NONE         : int = ...
GETKEY_DEFAULT      : int = ...
KEYEV_NONE          : int = ...
KEYEV_DOWN          : int = ...
KEYEV_UP            : int = ...
KEYEV_HOLD          : int = ...
KEY_F1              : int = ...
KEY_F2              : int = ...
KEY_F3              : int = ...
KEY_F4              : int = ...
KEY_F5              : int = ...
KEY_F6              : int = ...
KEY_SHIFT           : int = ...
KEY_OPTN            : int = ...
KEY_VARS            : int = ...
KEY_MENU            : int = ...
KEY_LEFT            : int = ...
KEY_UP              : int = ...
KEY_ALPHA           : int = ...
KEY_SQUARE          : int = ...
KEY_POWER           : int = ...
KEY_EXIT            : int = ...
KEY_DOWN            : int = ...
KEY_RIGHT           : int = ...
KEY_XOT             : int = ...
KEY_LOG             : int = ...
KEY_LN              : int = ...
KEY_SIN             : int = ...
KEY_COS             : int = ...
KEY_TAN             : int = ...
KEY_FRAC            : int = ...
KEY_FD              : int = ...
KEY_LEFTP           : int = ...
KEY_RIGHTP          : int = ...
KEY_COMMA           : int = ...
KEY_ARROW           : int = ...
KEY_7               : int = ...
KEY_8               : int = ...
KEY_9               : int = ...
KEY_DEL             : int = ...
KEY_4               : int = ...
KEY_5               : int = ...
KEY_6               : int = ...
KEY_MUL             : int = ...
KEY_DIV             : int = ...
KEY_1               : int = ...
KEY_2               : int = ...
KEY_3               : int = ...
KEY_ADD             : int = ...
KEY_SUB             : int = ...
KEY_0               : int = ...
KEY_DOT             : int = ...
KEY_EXP             : int = ...
KEY_NEG             : int = ...
KEY_EXE             : int = ...
KEY_ACON            : int = ...
KEY_HELP            : int = ...
KEY_LIGHT           : int = ...
KEY_X2              : int = ...
KEY_CARET           : int = ...
KEY_SWITCH          : int = ...
KEY_LEFTPAR         : int = ...
KEY_RIGHTPAR        : int = ...
KEY_STORE           : int = ...
KEY_TIMES           : int = ...
KEY_PLUS            : int = ...
KEY_MINUS           : int = ...

class buffer_like(str | bytes | bytearray): ...
class DTEXT_(int): ...
class C_(int): ...
class IMAGE_(int): ...
class GETKEY_(int): ...
class KEYEV_(int): ...
class KEY_(int): ...

class image:
    def __init__(self, profile: IMAGE_, width: int, height: int, data: buffer_like): ...
class key_event:
    time    : int
    mod     : bool
    shift   : bool
    alpha   : bool
    type    : KEYEV_
    key     : KEY_

def dupdate() -> None: ...
def dclear(color: C_) -> None: ...
def drect(x1: int, y1: int, x2: int, y2: int, color: C_) -> None: ...
def drect_border(x1: int, y1: int, x2: int, y2: int, fill_color: C_, border_width: int, border_color: C_) -> None: ...
def dpixel(x: int, y: int, color: C_) -> None: ...
def dgetpixel(x: int, y: int) -> int: ...
def dline(x1: int, y1: int, x2: int, y2: int, color: C_) -> None: ...
def dhline(y: int, color: C_) -> None: ...
def dvline(x: int, color: C_) -> None: ...
def dtext_opt(x: int, y: int, fg: int, bg: int, halign: int, valign: int, str: str, size: int) -> None: ...
def dtext(x: int, y: int, fg: int, str: str) -> None: ...
def dimage(x: int, y: int, image: image) -> None: ...
def dsubimage(x: int, y: int, image: image, left: int, top: int, width: int, height: int) -> None: ...
def image_rgb565(width: int, height: int, data: buffer_like) -> image: ...
def image_rgb565a(width: int, height: int, data: buffer_like) -> image: ...
def image_p8_rgb565(width: int, height: int, data: buffer_like, palette: buffer_like) -> image: ...
def image_p8_rgb565a(width: int, height: int, data: buffer_like, palette: buffer_like) -> image: ...
def image_p4_rgb565(width: int, height: int, data: buffer_like, palette: buffer_like) -> image: ...
def image_p4_rgb565a(width: int, height: int, data: buffer_like, palette: buffer_like) -> image: ...
def getkey() -> key_event: ...
def getkey_opt(opts: GETKEY_, timeout_ms: int | None) -> key_event: ...
def pollevent() -> key_event: ...
def waitevent() -> key_event: ...
def clearevents() -> None: ...
def keydown(key: KEY_) -> bool: ...
def keydown_all(*keys: KEY_) -> bool: ...
def keydown_any(*keys: KEY_) -> bool: ...
def cleareventflips() -> None: ...
def keypressed(key: KEY_) -> bool: ...
def keyreleased(key: KEY_) -> bool: ...
def keycode_function(key: KEY_) -> int: ...
def keycode_digit(key: KEY_) -> int: ...
